### ISSUE TITLE
Wrong asset URL in production build

### ISSUE THREAD

**Issue by wrapperup** [swlynch99/vite-plugin-css-url#1]
Heyo, this plugin is really nice and exactly what I need. However, when building for production, the asset URL isn't quite right.

Here's what I mean:

![image](https://github.com/swlynch99/vite-plugin-css-url/assets/7478134/a3c05621-5526-4505-937e-c6dd9d27fd3a)

I was able to modify the plugin to fix it changing line 103 and 106 in index.ts to this, which takes advantage of Vite's internal marker for assets, allowing it to be processed correctly as any other Vite asset:
```ts
const referenceId = this.emitFile({
    type: 'asset',
    name: assetName,
    source: content,
    // needsCodeReference: true
});

return `export default "__VITE_ASSET__${referenceId}__";`
```

Which now produces the correct URL

![image](https://github.com/swlynch99/vite-plugin-css-url/assets/7478134/8d519787-082c-48e8-82d8-758bb6186494)

Was there any specific reason it's like this? Would be great to fix, I can whip up a PR if needed.

**Comment by swlynch99** [comment]
Wierd. The old way seems to generate the right URL in my vite setup. The change in #2 does look like the right thing to do though.
